// Action Types
export default {
  // Facts Action Types
  FILTER_FACT_BY_TEXT: 'FILTER_FACT_BY_TEXT',
  // user_data Action Types
  // Favourites Action Types
  FILTER_FAVOURITE_FACT_BY_TEXT: 'FILTER_FAVOURITE_FACT_BY_TEXT',
  SAVE_FAVOURITE_FACT: 'SAVE_FAVOURITE_FACT',
  REMOVE_FAVOURITE_FACT: 'REMOVE_FAVOURITE_FACT',
  // my_facts
  FILTER_MY_FACTS_BY_TEXT: 'FILTER_MY_FACTS_BY_TEXT',
  ADD_NEW_FACT: 'ADD_NEW_FACT',
  REMOVE_MY_FACT: 'REMOVE_MY_FACT',
};
