// Action Types
export default {
  // Facts Action Types
  FILTER_FACT_BY_TEXT: 'FILTER_FACT_BY_TEXT',
  SAVE_FAVOURITE_FACT: 'SAVE_FAVOURITE_FACT',
  REMOVE_FAVOURITE_FACT: 'REMOVE_FAVOURITE_FACT',
};
